# Generated by Django 5.0.7 on 2024-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("project_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "thank_you_page",
                    models.URLField(default="http://example.com/thank-you"),
                ),
            ],
        ),
    ]
