# Generated by Django 5.0.7 on 2024-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="thank_you_page",
            field=models.URLField(blank=True, null=True),
        ),
    ]
